POST https://services.fulfillment.digital/fm/services/BusinessLink.asmx
Content-Type: text/xml;charset=utf-8
SOAPAction: http://www.myfactory.de/gbCallCustomerBusinessLinkMethod

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <gbCallCustomerBusinessLinkMethod xmlns="http://www.myfactory.de/">
      <sAccessArea>{{$dotenv ACCESS_AREA}}</sAccessArea>
      <sCustomerNumber>{{$dotenv CUSTOMER_NUMBER}}</sCustomerNumber>
      <sPassword>{{$dotenv PASSWORD}}</sPassword>
      <sMethod>WebShopProductImport</sMethod>
      <sParams>
        &lt;Products&gt;
          &lt;Product&gt;
            &lt;ProductID&gt;44441412272355&lt;/ProductID&gt;
            &lt;ProductNumber&gt;44441412272355&lt;/ProductNumber&gt;
            &lt;BaseUnit&gt;Stk&lt;/BaseUnit&gt;
            &lt;Name1&gt;&lt;![CDATA[Refill BB Cream 10 Alabaster]]&gt;&lt;/Name1&gt;
            &lt;Texation&gt;1&lt;/Texation&gt;
            &lt;EAN&gt;618119349875&lt;/EAN&gt;
          &lt;/Product&gt;
          &lt;Product&gt;
            &lt;ProductID&gt;44441412305123&lt;/ProductID&gt;
            &lt;ProductNumber&gt;44441412305123&lt;/ProductNumber&gt;
            &lt;BaseUnit&gt;Stk&lt;/BaseUnit&gt;
            &lt;Name1&gt;&lt;![CDATA[Refill BB Cream 20 Sand]]&gt;&lt;/Name1&gt;
            &lt;Texation&gt;1&lt;/Texation&gt;
            &lt;EAN&gt;618119349882&lt;/EAN&gt;
          &lt;/Product&gt;
          &lt;Product&gt;
            &lt;ProductID&gt;44441412337891&lt;/ProductID&gt;
            &lt;ProductNumber&gt;44441412337891&lt;/ProductNumber&gt;
            &lt;BaseUnit&gt;Stk&lt;/BaseUnit&gt;
            &lt;Name1&gt;&lt;![CDATA[Refill BB Cream 30 Ginger]]&gt;&lt;/Name1&gt;
            &lt;Texation&gt;1&lt;/Texation&gt;
            &lt;EAN&gt;618119349899&lt;/EAN&gt;
          &lt;/Product&gt;
          &lt;Product&gt;
            &lt;ProductID&gt;44441412370659&lt;/ProductID&gt;
            &lt;ProductNumber&gt;44441412370659&lt;/ProductNumber&gt;
            &lt;BaseUnit&gt;Stk&lt;/BaseUnit&gt;
            &lt;Name1&gt;&lt;![CDATA[Refill BB Cream 40 Golden]]&gt;&lt;/Name1&gt;
            &lt;Texation&gt;1&lt;/Texation&gt;
            &lt;EAN&gt;618119349905&lt;/EAN&gt;
          &lt;/Product&gt;
        &lt;/Products&gt;
      </sParams>

    </gbCallCustomerBusinessLinkMethod>
  </soap:Body>
</soap:Envelope>
